### ISSUE TITLE
Dangerous statement about modules prefixed with jdk

### ISSUE THREAD

**Issue by mipastgt** [justinmahar/easyjre#1]
The statement

> The modules prefixed with jdk. are typically not needed for a production JRE.

is dangerous. For example, if you don't include `jdk.crypto.ec`, your resulting code will not be able to perform https requests because this module implements all the elliptic curve crypto stuff needed to do so. It is used via a Serive which is loaded at run-time. So you will not notice the missing module at build time.

**Comment by justinmahar** [comment]
Thanks for pointing this out. I've changed the wording slightly so as not to mislead the developer into thinking they're good to go without some additional knowledge and forethought.

**Comment by justinmahar** [comment]
I've changed the wording to the following:

> The JDK comes with many modules which contain the JDK core classes. Below, all modules that aren't prefixed with `jdk.` have been included in the JRE. This will get you up and running quickly without needing to use an entire JDK. From there, you can pick and choose the JDK modules your project depends on.

CI/CD deployed: https://justinmahar.github.io/easyjre/
